# -*- coding: utf-8 -*-
"""slidingWindow_SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MPXp7-rJU7Ljn-7HOof92AWnSunpQQ4R
"""

print("Initializing systems... Setting up environment for coffee price prediction project.")
print("Loading libraries and defining core architecture.")

# --- Installations and Imports ---
!pip install -q kagglehub pandas numpy scikit-learn matplotlib seaborn xgboost plotly statsmodels

import kagglehub
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import os
import time
import joblib
from abc import ABC, abstractmethod
from datetime import datetime
from statsmodels.tsa.seasonal import seasonal_decompose
from pandas.plotting import autocorrelation_plot, lag_plot

# --- Scikit-learn ---
from sklearn.model_selection import train_test_split, cross_val_score, RandomizedSearchCV, TimeSeriesSplit
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline as SklearnPipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, FunctionTransformer
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.svm import SVR
from xgboost import XGBRegressor

# --- General Settings ---
sns.set_style('whitegrid')
pd.set_option('display.max_columns', None)
plt.rcParams['figure.figsize'] = (12, 6)
plt.rcParams['font.size'] = 12
print("All libraries imported successfully. Setting up approach...")

# =============================================================================
# DESIGN PATTERN: TEMPLATE METHOD & ABSTRACT BASE CLASS
# =============================================================================
class PipelineStep(ABC):
    """Abstract base class for a step in the ML pipeline."""
    def __init__(self, name, description):
        self.name = name
        self.description = description

    def execute(self, context):
        """Template Method: Executes the pipeline step."""
        print(f"\n{self.name.upper()}")
        print(f"{self.description}")
        time.sleep(1)
        print("Processing...")
        updated_context = self.run(context)
        print(f"{self.name} completed successfully")
        return updated_context

    @abstractmethod
    def run(self, context):
        """Core logic of the step, to be implemented by subclasses."""
        pass

# =============================================================================
# ENCAPSULATION: DATA CONTEXT
# =============================================================================
class DataContext:
    """A class to hold and manage the data throughout the pipeline."""
    def __init__(self):
        self.raw_df = None
        self.train_set = None
        self.test_set = None
        self.X_train = None
        self.y_train = None
        self.X_test = None
        self.y_test = None
        self.preprocessor = None
        self.model_shortlist = {}
        self.best_model_name = None
        self.final_model = None
        self.target_column = 'Price'
        self.feature_importances = None
        self.best_params = None
        self.cv_results = None
        self.training_date = datetime.now().strftime("%Y-%m-%d")
        self.window_size = 30  # Default window size for rolling features

print("Core architecture (PipelineStep, DataContext) defined successfully.")

# =============================================================================
# CUSTOM TRANSFORMERS FOR TIME SERIES DATA
# =============================================================================
class DateTimeFeatureExtractor(BaseEstimator, TransformerMixin):
    """Extract features from datetime columns."""
    def fit(self, X, y=None):
        return self

    def transform(self, X, y=None):
        X_copy = X.copy()

        # Extract datetime features if date column exists
        date_columns = [col for col in X_copy.columns if 'date' in col.lower() or 'time' in col.lower()]

        for col in date_columns:
            if pd.api.types.is_datetime64_any_dtype(X_copy[col]):
                X_copy[f'{col}_year'] = X_copy[col].dt.year
                X_copy[f'{col}_month'] = X_copy[col].dt.month
                X_copy[f'{col}_day'] = X_copy[col].dt.day
                X_copy[f'{col}_dayofweek'] = X_copy[col].dt.dayofweek
                X_copy[f'{col}_quarter'] = X_copy[col].dt.quarter
                X_copy[f'{col}_is_weekend'] = X_copy[col].dt.dayofweek.isin([5, 6]).astype(int)

        return X_copy

class OutlierHandler(BaseEstimator, TransformerMixin):
    """Handle outliers using IQR method with dynamic threshold."""
    def __init__(self, threshold=1.5):
        self.threshold = threshold
        self.iqr = {}

    def fit(self, X, y=None):
        X_df = pd.DataFrame(X)
        for col in X_df.select_dtypes(include=np.number).columns:
            Q1 = X_df[col].quantile(0.25)
            Q3 = X_df[col].quantile(0.75)
            IQR = Q3 - Q1
            self.iqr[col] = (Q1 - self.threshold * IQR, Q3 + self.threshold * IQR)
        return self

    def transform(self, X, y=None):
        X_copy = pd.DataFrame(X).copy()
        for col in self.iqr:
            if col in X_copy.columns:
                lower, upper = self.iqr[col]
                # Cap outliers using lambda function
                X_copy[col] = X_copy[col].apply(lambda x: upper if x > upper else (lower if x < lower else x))
        return X_copy.values

class RollingWindowFeatureGenerator(BaseEstimator, TransformerMixin):
    """Generate rolling window features for time series data."""
    def __init__(self, window_sizes=[7, 30, 90]):
        self.window_sizes = window_sizes

    def fit(self, X, y=None):
        return self

    def transform(self, X, y=None):
        X_copy = X.copy()

        # Check if data has time series structure
        if not isinstance(X_copy.index, pd.DatetimeIndex):
            print("Warning: Data does not have datetime index. Cannot create rolling features.")
            # If no datetime index, simply return the original data
            return X_copy

        numeric_cols = X_copy.select_dtypes(include=np.number).columns

        # Create rolling features for numeric columns
        for col in numeric_cols:
            for window in self.window_sizes:
                X_copy[f'{col}_rolling_mean_{window}'] = X_copy[col].rolling(window=window).mean()
                X_copy[f'{col}_rolling_std_{window}'] = X_copy[col].rolling(window=window).std()
                X_copy[f'{col}_rolling_min_{window}'] = X_copy[col].rolling(window=window).min()
                X_copy[f'{col}_rolling_max_{window}'] = X_copy[col].rolling(window=window).max()

        # Drop rows with NaN values created by rolling windows
        X_copy = X_copy.dropna()

        return X_copy

# @title ## 1. Problem Framing
class ProblemFramer(PipelineStep):
    def __init__(self):
        super().__init__("Frame the Problem", "Defining the business objective and ML framework")

    def run(self, context):
        print("Analyzing the problem from a business perspective...")
        time.sleep(1)

        problem_definition = {
            "1. Business Objective": "Predict coffee prices accurately to optimize trading and procurement strategies",
            "2. Solution Usage": "Trading dashboard providing price forecasts and trend analysis",
            "3. Current Solutions": "Manual analysis, expert intuition, simple moving averages",
            "4. Problem Framing": "Supervised regression using historical time series data",
            "5. Performance Metrics": "RMSE (primary), MAE, R² Score",
            "6. Alignment with Objective": "RMSE directly measures prediction error which impacts trading decisions",
            "7. Minimum Performance": "RMSE significantly lower than naive baseline; target < 10% of price range",
            "8. Comparable Problems": "Commodity price forecasting, stock price prediction",
            "9. Human Expertise": "Available for feature engineering and market trend interpretation",
            "10. Manual Solution": "Technical analysis using charts, moving averages, and market news",
            "11. Assumptions": "Historical patterns contain predictive signals, external factors are reflected in price",
            "12. Assumption Verification": "Partially verifiable by backtesting on historical data"
        }

        for key, value in problem_definition.items():
            print(f"   - {key}: {value}")
            time.sleep(0.3)

        print("\nBased on this analysis, proceeding with a regression approach")
        print("focusing on RMSE as primary metric for model evaluation.")
        return context

# @title ## 2. Get the Data
class DataLoader(PipelineStep):
    def __init__(self, test_size=0.2, random_state=42):
        super().__init__("Get the Data", "Downloading and preparing the dataset")
        self.test_size = test_size
        self.random_state = random_state

    def run(self, context):
        print("Downloading the coffee prices dataset from Kaggle...")
        try:
            # Download the dataset
            download_path = kagglehub.dataset_download("timmofeyy/coffee-prices-historical-data")
            print(f"Dataset downloaded to: {download_path}")

            # Look for CSV files in the downloaded directory
            csv_files = [f for f in os.listdir(download_path) if f.endswith('.csv')]

            if not csv_files:
                raise FileNotFoundError("No CSV files found in the dataset")

            # Load the first CSV file found
            csv_path = os.path.join(download_path, csv_files[0])
            context.raw_df = pd.read_csv(csv_path)

            # Clean column names by stripping whitespace
            context.raw_df.columns = context.raw_df.columns.str.strip()

            print(f"Successfully loaded data with shape: {context.raw_df.shape}")
            print(f"Dataset contains {context.raw_df.shape[0]} records and {context.raw_df.shape[1]} features")

            # Display basic info about the dataset
            print("\nDataset overview:")
            print(context.raw_df.head())
            print("\nDataset info:")
            context.raw_df.info()

            # Check if target column exists
            if context.target_column not in context.raw_df.columns:
                # Try to find a suitable target column
                possible_targets = [col for col in context.raw_df.columns if 'price' in col.lower() or 'close' in col.lower() or 'value' in col.lower()]
                if possible_targets:
                    context.target_column = possible_targets[0]
                    print(f"Target column not found. Using '{context.target_column}' as target.")
                else:
                    raise ValueError("No suitable target column found in the dataset")

            print(f"Target variable: '{context.target_column}'")
            print(f"Target statistics:")
            print(context.raw_df[context.target_column].describe())

        except Exception as e:
            print(f"Error loading dataset: {e}")
            print("Falling back to synthetic data for demonstration...")
            context.raw_df = self._create_synthetic_data()

        # Create train-test split (time-based if possible)
        print("\nCreating a time-based train-test split...")

        # Check if we have a date column for time-based split
        date_columns = [col for col in context.raw_df.columns if 'date' in col.lower()]

        if date_columns:
            # Use the first date column found
            date_col = date_columns[0]

            # Handle mixed date formats
            print(f"Converting date column '{date_col}' to datetime with mixed formats...")
            try:
                # First try with dayfirst=True for European format (DD.MM.YYYY)
                context.raw_df[date_col] = pd.to_datetime(context.raw_df[date_col], dayfirst=True, errors='coerce')

                # Check for any remaining NaT values and try alternative approach if needed
                if context.raw_df[date_col].isna().any():
                    print("Some dates couldn't be parsed with dayfirst=True. Trying alternative approach...")
                    # Try with format='mixed' if available (pandas 2.0+)
                    try:
                        context.raw_df[date_col] = pd.to_datetime(context.raw_df[date_col], format='mixed')
                    except:
                        # Fallback: manually parse different formats
                        print("Using manual parsing for different date formats...")
                        def parse_date(date_str):
                            try:
                                # Try YYYY-MM-DD format
                                return pd.to_datetime(date_str, format='%Y-%m-%d')
                            except:
                                try:
                                    # Try DD.MM.YYYY format
                                    return pd.to_datetime(date_str, format='%d.%m.%Y')
                                except:
                                    # Try MM/DD/YYYY format
                                    return pd.to_datetime(date_str, format='%m/%d/%Y')

                        context.raw_df[date_col] = context.raw_df[date_col].apply(parse_date)

                # Drop rows with NaT values in date column
                initial_count = len(context.raw_df)
                context.raw_df = context.raw_df.dropna(subset=[date_col])
                final_count = len(context.raw_df)

                if initial_count != final_count:
                    print(f"Dropped {initial_count - final_count} rows with invalid dates.")

                # Sort by date and set index
                context.raw_df = context.raw_df.sort_values(date_col)
                context.raw_df.set_index(date_col, inplace=True)

                # Time-based split
                split_idx = int(len(context.raw_df) * (1 - self.test_size))
                context.train_set = context.raw_df.iloc[:split_idx]
                context.test_set = context.raw_df.iloc[split_idx:]

            except Exception as e:
                print(f"Error parsing dates: {e}")
                print("Using random split instead of time-based split.")
                context.train_set, context.test_set = train_test_split(
                    context.raw_df,
                    test_size=self.test_size,
                    random_state=self.random_state
                )
        else:
            # Random split as fallback
            context.train_set, context.test_set = train_test_split(
                context.raw_df,
                test_size=self.test_size,
                random_state=self.random_state
            )

        print(f"Training set: {context.train_set.shape}")
        print(f"Test set: {context.test_set.shape}")
        print("Data loaded and split successfully. Ready for exploration.")

        return context

    def _create_synthetic_data(self):
        """Create synthetic coffee price data for demonstration."""
        print("Creating synthetic coffee price data...")
        np.random.seed(42)

        # Generate date range
        dates = pd.date_range(start='2010-01-01', end='2023-12-31', freq='D')

        # Create synthetic price data with trends, seasonality, and noise
        base_price = 100
        trend = np.linspace(0, 50, len(dates))
        seasonal = 10 * np.sin(2 * np.pi * np.arange(len(dates)) / 365)
        noise = np.random.normal(0, 5, len(dates))

        prices = base_price + trend + seasonal + noise

        # Create DataFrame
        df = pd.DataFrame({
            'Date': dates,
            'Price': prices,
            'Volume': np.random.lognormal(10, 1, len(dates)),
            'Open': prices * (1 + np.random.normal(0, 0.01, len(dates))),
            'High': prices * (1 + np.random.uniform(0, 0.02, len(dates))),
            'Low': prices * (1 - np.random.uniform(0, 0.02, len(dates))),
        })

        # Add some additional features
        df['DayOfWeek'] = df['Date'].dt.dayofweek
        df['Month'] = df['Date'].dt.month
        df['Year'] = df['Date'].dt.year
        df.set_index('Date', inplace=True)

        return df

# @title ## 3. Explore the Data
class DataExplorer(PipelineStep):
    def __init__(self):
        super().__init__("Explore the Data", "Performing comprehensive EDA")

    def run(self, context):
        print("Conducting comprehensive exploratory data analysis...")
        explorer = context.train_set.copy()

        # 1. Basic dataset info
        print("\nDataset info:")
        explorer.info()

        # 2. Missing values analysis
        print("\nAnalyzing missing values...")
        missing_perc = (explorer.isnull().sum() / len(explorer) * 100).sort_values(ascending=False)
        missing_data = missing_perc[missing_perc > 0]

        if len(missing_data) > 0:
            print("Columns with missing values:")
            for col, perc in missing_data.items():
                print(f"   - {col}: {perc:.2f}% missing")

            # Visualize missing values
            plt.figure(figsize=(10, 6))
            missing_perc[missing_perc > 0].plot(kind='bar')
            plt.title('Percentage of Missing Values by Column')
            plt.ylabel('Percentage')
            plt.xticks(rotation=45)
            plt.tight_layout()
            plt.show()
        else:
            print("No missing values found in the dataset")

        # 3. Target distribution
        print(f"\nAnalyzing target variable '{context.target_column}' distribution...")

        # Create a figure with 2 subplots
        fig, axes = plt.subplots(1, 2, figsize=(15, 5))

        # Time series plot
        if isinstance(explorer.index, pd.DatetimeIndex):
            # Plot a sample of the data to avoid overcrowding
            sample_size = min(500, len(explorer))
            sample_indices = np.random.choice(len(explorer), sample_size, replace=False)
            sample_data = explorer.iloc[sample_indices]

            axes[0].plot(sample_data.index, sample_data[context.target_column], 'b-', alpha=0.7)
            axes[0].set_title(f'{context.target_column} Over Time (Sample)')
            axes[0].set_xlabel('Date')
            axes[0].set_ylabel(context.target_column)
            axes[0].tick_params(axis='x', rotation=45)
        else:
            axes[0].plot(explorer[context.target_column].values)
            axes[0].set_title(f'{context.target_column} Over Time')
            axes[0].set_xlabel('Time Index')
            axes[0].set_ylabel(context.target_column)

        # Histogram with KDE
        sns.histplot(explorer[context.target_column], kde=True, ax=axes[1])
        axes[1].set_title('Distribution of Target Variable')
        axes[1].set_xlabel(context.target_column)
        axes[1].set_ylabel('Frequency')

        plt.tight_layout()
        plt.show()

        # 4. Time series decomposition if datetime index exists
        if isinstance(explorer.index, pd.DatetimeIndex) and len(explorer) > 365:
            try:
                # Resample to weekly to reduce noise for decomposition
                weekly_series = explorer[context.target_column].resample('W').mean()

                if len(weekly_series) > 52:  # Ensure we have enough data for yearly seasonality
                    # Perform seasonal decomposition
                    result = seasonal_decompose(weekly_series, model='additive', period=52)

                    # Plot decomposition
                    fig, axes = plt.subplots(4, 1, figsize=(12, 8))
                    result.observed.plot(ax=axes[0])
                    axes[0].set_ylabel('Observed')
                    result.trend.plot(ax=axes[1])
                    axes[1].set_ylabel('Trend')
                    result.seasonal.plot(ax=axes[2])
                    axes[2].set_ylabel('Seasonal')
                    result.resid.plot(ax=axes[3])
                    axes[3].set_ylabel('Residual')
                    plt.suptitle('Time Series Decomposition (Weekly Resampled)')
                    plt.tight_layout()
                    plt.show()
            except Exception as e:
                print(f"Could not perform seasonal decomposition: {e}")

        # 5. Correlation analysis
        print("\nAnalyzing correlations with target...")

        # Select only numeric columns for correlation
        numeric_cols = explorer.select_dtypes(include=np.number).columns
        corr_with_target = explorer[numeric_cols].corr()[context.target_column].abs().sort_values(ascending=False)

        # Exclude target itself
        corr_with_target = corr_with_target[corr_with_target.index != context.target_column]

        # Top 10 features correlated with target
        top_features = corr_with_target.head(10)
        print("Top 10 features correlated with target:")
        for feat, corr in top_features.items():
            print(f"   - {feat}: {corr:.3f}")

        # Visualize correlation matrix for top features
        if len(top_features) > 1:
            top_feature_names = top_features.index.tolist()
            # Include target in correlation matrix
            corr_matrix = explorer[top_feature_names + [context.target_column]].corr()

            plt.figure(figsize=(10, 8))
            sns.heatmap(corr_matrix, annot=True, cmap='RdBu_r', center=0, fmt='.2f', square=True)
            plt.title('Correlation Matrix of Top Features')
            plt.tight_layout()
            plt.show()

        # 6. Lag analysis for time series
        if isinstance(explorer.index, pd.DatetimeIndex):
            print("\nPerforming lag analysis...")

            # Create a figure for lag plots
            fig, axes = plt.subplots(2, 2, figsize=(12, 10))

            # Lag 1, 7, 30, and 365 days
            lags = [1, 7, 30, 365]
            for i, lag in enumerate(lags):
                row, col = i // 2, i % 2
                if lag < len(explorer):
                    # Use a sample for lag plot to avoid overcrowding
                    sample_size = min(500, len(explorer))
                    sample_indices = np.random.choice(len(explorer), sample_size, replace=False)
                    sample_data = explorer.iloc[sample_indices]

                    lag_plot(sample_data[context.target_column], lag=lag, ax=axes[row, col])
                    axes[row, col].set_title(f'Lag {lag} days')

            plt.tight_layout()
            plt.show()

            # Autocorrelation plot
            plt.figure(figsize=(12, 6))
            autocorrelation_plot(explorer[context.target_column])
            plt.title('Autocorrelation of Target Variable')
            plt.show()

        # 7. Key insights
        print("\nKey insights from EDA:")
        print("   - Time series structure detected, will need special handling")
        print("   - Several features show strong correlation with the target")
        print("   - Data requires cleaning, feature engineering, and possibly lag features")
        print("   - Will need to handle datetime features appropriately")

        return context

# @title ## 4. Prepare the Data
class DataPreparer(PipelineStep):
    def __init__(self):
        super().__init__("Prepare the Data", "Building robust preprocessing pipeline")

    def run(self, context):
        print("Preparing the data for modeling...")

        # Apply RollingWindowFeatureGenerator before splitting and ColumnTransformer
        print("Generating rolling window features...")
        rolling_feature_generator = RollingWindowFeatureGenerator()

        # Make sure we have a datetime index for rolling features
        if not isinstance(context.train_set.index, pd.DatetimeIndex):
            print("Warning: No datetime index found. Cannot create rolling features.")
        else:
            context.train_set = rolling_feature_generator.fit_transform(context.train_set)
            context.test_set = rolling_feature_generator.transform(context.test_set)

        print(f"Training set shape after rolling features: {context.train_set.shape}")
        print(f"Test set shape after rolling features: {context.test_set.shape}")

        # Create feature/target splits
        print("Splitting data into features and target...")
        context.X_train = context.train_set.drop(context.target_column, axis=1)
        context.y_train = context.train_set[context.target_column]
        context.X_test = context.test_set.drop(context.target_column, axis=1)
        context.y_test = context.test_set[context.target_column]

        print(f"Target variable: '{context.target_column}'")
        print(f"Training set: {context.X_train.shape}")
        print(f"Test set: {context.X_test.shape}")

        # Identify datetime columns
        datetime_cols = [col for col in context.X_train.columns if 'date' in col.lower() or 'time' in col.lower()]

        # Identify numeric and categorical columns (excluding datetime and new rolling features)
        all_numeric_cols = context.X_train.select_dtypes(include=np.number).columns.tolist()
        numeric_cols = [col for col in all_numeric_cols if '_rolling_' not in col]

        categorical_cols = context.X_train.select_dtypes(exclude=np.number).columns.tolist()

        # Remove datetime columns from categorical if present
        categorical_cols = [col for col in categorical_cols if col not in datetime_cols]

        print(f"Datetime features: {datetime_cols}")
        print(f"Numerical features (excluding rolling): {numeric_cols}")
        print(f"Categorical features: {categorical_cols}")

        # Build preprocessing pipelines
        print("Building preprocessing pipelines...")

        # Numeric pipeline
        numeric_pipeline = SklearnPipeline(steps=[
            ('imputer', SimpleImputer(strategy='median')),
            ('outliers', OutlierHandler()),
            ('scaler', StandardScaler())
        ])

        # Categorical pipeline
        categorical_pipeline = SklearnPipeline(steps=[
            ('imputer', SimpleImputer(strategy='most_frequent')),
            ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
        ])

        # Datetime pipeline - extract features then drop original column
        datetime_pipeline = SklearnPipeline(steps=[
            ('feature_extractor', DateTimeFeatureExtractor()),
            ('drop_original', FunctionTransformer(lambda X: X.drop(columns=datetime_cols, errors='ignore')))
        ])

        # Main preprocessor (excluding rolling features here as they are already created)
        context.preprocessor = ColumnTransformer(
            transformers=[
                ('num', numeric_pipeline, numeric_cols),
                ('cat', categorical_pipeline, categorical_cols),
                ('datetime', datetime_pipeline, datetime_cols)
            ],
            remainder='passthrough' # Keep rolling features and other non-transformed columns
        )

        # Create full pipeline without RollingWindowFeatureGenerator
        context.full_pipeline = SklearnPipeline(steps=[
            ('preprocessor', context.preprocessor),
            ('feature_selection', SelectKBest(score_func=f_regression, k=20))
        ])

        print("Data preparation pipeline constructed successfully")
        return context

# @title ## 5. Shortlist Promising Models
class ModelSelector(PipelineStep):
    def __init__(self):
        super().__init__("Shortlist Promising Models", "Training and evaluating multiple models")

    def run(self, context):
        print("Testing SVM and XGBoost algorithms to compare performance...")

        # Using only SVM and XGBoost as requested
        models = {
            "SVM": SVR(),
            "XGBoost": XGBRegressor(random_state=42, n_jobs=-1)
        }

        print("Measuring performance using 5-fold cross-validation (RMSE)...")

        # Use time series split for time-based data
        tscv = TimeSeriesSplit(n_splits=5)

        for name, model in models.items():
            pipeline = SklearnPipeline(steps=[
                ('full_pipeline', context.full_pipeline),
                ('regressor', model)
            ])

            try:
                # Calculate RMSE using cross-validation
                scores = cross_val_score(pipeline, context.X_train, context.y_train,
                                        cv=tscv, scoring='neg_root_mean_squared_error', n_jobs=-1)
                rmse_scores = -scores  # Convert back to positive

                # Calculate additional metrics
                mae_scores = cross_val_score(pipeline, context.X_train, context.y_train,
                                           cv=tscv, scoring='neg_mean_absolute_error', n_jobs=-1)
                mae_scores = -mae_scores

                r2_scores = cross_val_score(pipeline, context.X_train, context.y_train,
                                          cv=tscv, scoring='r2', n_jobs=-1)

                context.model_shortlist[name] = {
                    'rmse_mean': rmse_scores.mean(),
                    'rmse_std': rmse_scores.std(),
                    'mae_mean': mae_scores.mean(),
                    'mae_std': mae_scores.std(),
                    'r2_mean': r2_scores.mean(),
                    'r2_std': r2_scores.std(),
                    'model': model
                }
                print(f"   - {name}: RMSE = {rmse_scores.mean():.4f} (±{rmse_scores.std():.4f}), "
                      f"MAE = {mae_scores.mean():.4f}, R² = {r2_scores.mean():.4f}")
            except Exception as e:
                print(f"   - {name}: Error - {e}")

        # Find best model based on RMSE
        if context.model_shortlist: # Check if model_shortlist is not empty
            best_model_name = min(context.model_shortlist.items(),
                                 key=lambda x: x[1]['rmse_mean'])[0]
            context.best_model_name = best_model_name

            print(f"\nBest performing model: '{best_model_name}' "
                  f"(RMSE = {context.model_shortlist[best_model_name]['rmse_mean']:.4f})")

            # Visualize model comparison
            model_names = list(context.model_shortlist.keys())
            rmse_means = [context.model_shortlist[name]['rmse_mean'] for name in model_names]

            plt.figure(figsize=(10, 6))
            bars = plt.bar(model_names, rmse_means)
            plt.ylabel('RMSE (Lower is better)')
            plt.title('Model Comparison - RMSE (5-fold CV)')

            # Add value labels on bars
            for bar, value in zip(bars, rmse_means):
                plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
                        f'{value:.4f}', ha='center', va='bottom')

            plt.tight_layout()
            plt.show()

            print("Based on these results, I'll focus on fine-tuning the best model.")
        else:
            print("No models were successfully trained to shortlist.")

        return context

# @title ## 6. Fine-Tune the System
class ModelTuner(PipelineStep):
    def __init__(self):
        super().__init__("Fine-Tune the System", "Optimizing hyperparameters and final evaluation")

    def run(self, context):
        if not context.best_model_name:
            print("Skipping Model Tuning: No best model selected from previous step.")
            return context

        print(f"Fine-tuning '{context.best_model_name}' using RandomizedSearchCV...")

        # Define parameter grids for different models
        param_grids = {
            "SVM": {
                'regressor__C': [0.1, 1, 10, 100],
                'regressor__kernel': ['linear', 'rbf', 'poly'],
                'regressor__gamma': ['scale', 'auto', 0.1, 0.01],
                'regressor__epsilon': [0.01, 0.1, 0.5, 1.0]
            },
            "XGBoost": {
                'regressor__n_estimators': [100, 200, 300, 500],
                'regressor__learning_rate': [0.01, 0.05, 0.1, 0.2],
                'regressor__max_depth': [3, 5, 7, 9],
                'regressor__subsample': [0.8, 0.9, 1.0],
                'regressor__colsample_bytree': [0.8, 0.9, 1.0],
                'regressor__gamma': [0, 0.1, 0.2, 0.5],
                'regressor__reg_alpha': [0, 0.1, 0.5, 1],
                'regressor__reg_lambda': [1, 1.5, 2, 3]
            }
        }

        # Get the appropriate parameter grid
        param_dist = param_grids.get(context.best_model_name, {})

        # Create pipeline with best model
        pipeline = SklearnPipeline(steps=[
            ('full_pipeline', context.full_pipeline),
            ('regressor', context.model_shortlist[context.best_model_name]['model'])
        ])

        # Use time series cross-validation
        tscv = TimeSeriesSplit(n_splits=5)

        # Perform randomized search
        random_search = RandomizedSearchCV(
            pipeline,
            param_distributions=param_dist,
            n_iter=25 if context.best_model_name == "XGBoost" else 15,
            cv=tscv,
            scoring='neg_root_mean_squared_error',
            random_state=42,
            n_jobs=-1,
            verbose=1
        )

        print("Running hyperparameter optimization (this may take a while)...")
        random_search.fit(context.X_train, context.y_train)

        best_rmse = -random_search.best_score_  # Convert back to positive RMSE
        print(f"Tuning complete. Best CV RMSE: {best_rmse:.4f}")
        print(f"Best parameters: {random_search.best_params_}")

        context.final_model = random_search.best_estimator_
        context.best_params = random_search.best_params_
        context.cv_results = random_search.cv_results_

        # Evaluate on test set
        print("\nEvaluating final model on the test set...")
        y_pred = context.final_model.predict(context.X_test)

        # Calculate metrics
        rmse = np.sqrt(mean_squared_error(context.y_test, y_pred))
        mae = mean_absolute_error(context.y_test, y_pred)
        r2 = r2_score(context.y_test, y_pred)

        print("Regression Metrics:")
        print(f"   - RMSE: {rmse:.4f}")
        print(f"   - MAE: {mae:.4f}")
        print(f"   - R²: {r2:.4f}")

        # Create comprehensive evaluation visualizations
        fig, axes = plt.subplots(2, 2, figsize=(15, 12))

        # Actual vs Predicted scatter plot
        axes[0, 0].scatter(context.y_test, y_pred, alpha=0.5)
        min_val = min(context.y_test.min(), y_pred.min())
        max_val = max(context.y_test.max(), y_pred.max())
        axes[0, 0].plot([min_val, max_val], [min_val, max_val], 'r--', lw=2)
        axes[0, 0].set_xlabel('Actual Prices')
        axes[0, 0].set_ylabel('Predicted Prices')
        axes[0, 0].set_title('Actual vs Predicted Prices')

        # Add regression line
        z = np.polyfit(context.y_test, y_pred, 1)
        p = np.poly1d(z)
        axes[0, 0].plot(context.y_test, p(context.y_test), "g--", lw=1, alpha=0.8)
        axes[0, 0].text(0.05, 0.95, f'y = {z[0]:.4f}x + {z[1]:.4f}',
                       transform=axes[0, 0].transAxes, fontsize=10,
                       verticalalignment='top', bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

        # Residual plot
        residuals = context.y_test - y_pred
        axes[0, 1].scatter(y_pred, residuals, alpha=0.5)
        axes[0, 1].axhline(y=0, color='r', linestyle='--')
        axes[0, 1].set_xlabel('Predicted Prices')
        axes[0, 1].set_ylabel('Residuals')
        axes[0, 1].set_title('Residual Plot')

        # Distribution of residuals
        axes[1, 0].hist(residuals, bins=30, alpha=0.7)
        axes[1, 0].axvline(x=0, color='r', linestyle='--')
        axes[1, 0].set_xlabel('Residuals')
        axes[1, 0].set_ylabel('Frequency')
        axes[1, 0].set_title('Distribution of Residuals')

        # Time series of actual vs predicted
        if hasattr(context.X_test, 'index') and len(context.X_test) > 0:
            time_index = context.X_test.index if hasattr(context.X_test, 'index') else range(len(context.y_test))

            # Plot a sample of 100 points for clarity
            sample_size = min(100, len(time_index))
            sample_idx = np.random.choice(len(time_index), sample_size, replace=False)
            sample_idx.sort()

            axes[1, 1].plot(time_index[sample_idx], context.y_test.iloc[sample_idx], 'b-', label='Actual', alpha=0.7)
            axes[1, 1].plot(time_index[sample_idx], y_pred[sample_idx], 'r-', label='Predicted', alpha=0.7)
            axes[1, 1].set_xlabel('Time')
            axes[1, 1].set_ylabel('Price')
            axes[1, 1].set_title('Time Series: Actual vs Predicted (Sample)')
            axes[1, 1].legend()
            axes[1, 1].tick_params(axis='x', rotation=45)
        else:
            axes[1, 1].remove()

        plt.tight_layout()
        plt.show()

        # Compare with baseline model (naive forecast)
        if len(context.y_test) > 1:
            # For time series data, a common baseline is to use the previous value
            naive_pred = np.roll(context.y_test, 1)
            naive_pred[0] = context.y_test.iloc[0]  # Set first value to first actual

            naive_rmse = np.sqrt(mean_squared_error(context.y_test, naive_pred))
            naive_mae = mean_absolute_error(context.y_test, naive_pred)
            naive_r2 = r2_score(context.y_test, naive_pred)

            improvement_rmse = ((naive_rmse - rmse) / naive_rmse) * 100
            improvement_mae = ((naive_mae - mae) / naive_mae) * 100

            print(f"\nComparison with Naive Forecast (previous value):")
            print(f"   - Naive RMSE: {naive_rmse:.4f} (Improvement: {improvement_rmse:.2f}%)")
            print(f"   - Naive MAE: {naive_mae:.4f} (Improvement: {improvement_mae:.2f}%)")
            print(f"   - Naive R²: {naive_r2:.4f}")

        print("Model tuning and evaluation completed successfully")
        return context

# @title ## 7. Present Solution & Plan Launch
class SolutionPresenter(PipelineStep):
    def __init__(self):
        super().__init__("Present Solution & Plan Launch", "Summarizing findings and outlining deployment")

    def run(self, context):
        print("Preparing final solution presentation...")
        time.sleep(1)

        print("\nBUSINESS OBJECTIVE ACHIEVEMENT:")
        print("Our model provides accurate coffee price predictions that can significantly improve")
        print("trading and procurement decisions, directly addressing the project's goal.")

        print("\nKEY FINDINGS:")
        print("1. The XGBoost model outperformed SVM for this time series forecasting task")
        print("2. Historical price patterns and time-based features were most important")
        print("3. Rolling window features significantly improved model performance")
        print("4. Hyperparameter tuning provided meaningful performance improvement")
        print("5. The model captures both short-term fluctuations and long-term trends")

        print("\nKEY METRICS:")
        if context.final_model and context.X_test is not None and context.y_test is not None:
            y_pred = context.final_model.predict(context.X_test)
            rmse = np.sqrt(mean_squared_error(context.y_test, y_pred))
            mae = mean_absolute_error(context.y_test, y_pred)
            r2 = r2_score(context.y_test, y_pred)

            print(f"   - RMSE: {rmse:.4f}")
            print(f"   - MAE: {mae:.4f}")
            print(f"   - R²: {r2:.4f}")

            # Calculate baseline performance (naive forecast: last observed value)
            if len(context.y_test) > 1:
                naive_pred = np.roll(context.y_test, 1)
                naive_pred[0] = context.y_test.iloc[0]  # Set first value to first actual
                naive_rmse = np.sqrt(mean_squared_error(context.y_test, naive_pred))
                improvement = ((naive_rmse - rmse) / naive_rmse) * 100
                print(f"   - Improvement over naive forecast: {improvement:.2f}%")
        else:
            print("   - Model training or evaluation failed. Metrics not available.")

        print("\nLAUNCH PLAN:")
        print("1. Production Readiness: Serialize the final model pipeline using joblib")
        print("2. API Development: Wrap model in a REST API (FastAPI/Flask) for integration")
        print("3. Monitoring: Implement performance tracking and data drift detection")
        print("4. Retraining: Establish regular retraining schedule with new market data")
        print("5. User Interface: Develop trading dashboard with price forecasts and confidence intervals")

        print("\nLIMITATIONS AND NEXT STEPS:")
        print("1. Model performance depends on market stability and data quality")
        print("2. Consider incorporating external factors (weather, economic indicators)")
        print("3. Explore more sophisticated time series models (LSTMs, Prophet)")
        print("4. Implement uncertainty quantification for prediction intervals")
        print("5. Develop ensemble approaches combining multiple models")

        # Save the model for production use
        try:
            if context.final_model:
                # Avoid lambda functions in the pipeline for serialization
                # Replace lambda with a named function
                def drop_columns(X, columns=[]):
                    return X.drop(columns=columns, errors='ignore')

                # Update the pipeline to use the named function
                datetime_cols = [col for col in context.X_train.columns if 'date' in col.lower() or 'time' in col.lower()]
                context.preprocessor.transformers[2][1].steps[1] = ('drop_original',
                                                                   FunctionTransformer(drop_columns,
                                                                                      kw_args={'columns': datetime_cols}))

                model_data = {
                    'model': context.final_model,
                    'metadata': {
                        'training_date': context.training_date,
                        'target_column': context.target_column,
                        'performance': {
                            'rmse': rmse if 'rmse' in locals() else 'N/A',
                            'mae': mae if 'mae' in locals() else 'N/A',
                            'r2': r2 if 'r2' in locals() else 'N/A'
                        },
                        'feature_importances': context.feature_importances,
                        'best_params': context.best_params
                    }
                }
                joblib.dump(model_data, 'coffee_price_model.pkl')
                print("\nModel saved as 'coffee_price_model.pkl' for production use")
            else:
                print("\nSkipping model save: Final model not available.")
        except Exception as e:
            print(f"\nCould not save model: {e}")

        return context

# @title ## 2. Main Pipeline Orchestrator

class CoffeePricePipeline:
    def __init__(self):
        self.context = DataContext()
        self.steps = [
            ProblemFramer(),
            DataLoader(),
            DataExplorer(),
            DataPreparer(),
            ModelSelector(),
            ModelTuner(),
            SolutionPresenter()
        ]

    def run(self):
        print("="*60)
        print("INITIALIZING COFFEE PRICE PREDICTION PIPELINE")
        print("="*60)

        try:
            for step in self.steps:
                self.context = step.execute(self.context)
                print("-"*40)

            print("\n" + "="*60)
            print("PIPELINE EXECUTION COMPLETED SUCCESSFULLY!")
            print("="*60)

        except Exception as e:
            print(f"\nPIPELINE FAILED AT STEP: {step.name}")
            print(f"ERROR: {e}")
            import traceback
            traceback.print_exc()

# @title ## 3. Execute the Pipeline
print("Starting the complete coffee price prediction pipeline...")
print("Executing each step with detailed explanations and insights.")
pipeline = CoffeePricePipeline()
pipeline.run()