package com.elasticsearch.search.controller;

import com.elasticsearch.search.api.facade.SuggestApi;
import com.elasticsearch.search.api.model.SuggestResponse;
import com.elasticsearch.search.service.SearchService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RestController;

import java.util.concurrent.CompletableFuture;

/**
 * @brief REST controller for the /suggest endpoint.
 *
 * Implements the {@link SuggestApi} interface generated by the OpenAPI Generator.
 * Returns spelling correction suggestions based on the Elasticsearch Term Suggest
 * mechanism, enabling the "Did you mean?" feature in the UI.
 */
@CrossOrigin
@RestController
public class SuggestController implements SuggestApi {

    private final SearchService searchService;

    public SuggestController(SearchService searchService) {
        this.searchService = searchService;
    }

    /**
     * @brief Handles GET /suggest requests.
     *
     * @param query The user input potentially containing misspelled words (required).
     * @param size  Maximum number of suggestions per token (optional, defaults to 3).
     * @return A CompletableFuture resolving to a ResponseEntity with spelling suggestions.
     */
    @Override
    public CompletableFuture<ResponseEntity<SuggestResponse>> suggest(
            String query, Integer size) {

        return CompletableFuture.supplyAsync(() -> {
            SuggestResponse response = searchService.getSuggestions(query, size);
            return ResponseEntity.ok(response);
        });
    }
}
