package com.elasticsearch.search.controller;

import com.elasticsearch.search.api.facade.SearchApi;
import com.elasticsearch.search.api.model.SearchResponse;
import com.elasticsearch.search.service.SearchService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RestController;

import java.util.concurrent.CompletableFuture;

/**
 * @brief REST controller for the /search endpoint.
 *
 * Implements the {@link SearchApi} interface generated by the OpenAPI Generator
 * from the {@code api.yml} contract. Delegates search execution to the
 * {@link SearchService} and returns a fully populated {@link SearchResponse}.
 */
@CrossOrigin
@RestController
public class SearchController implements SearchApi {

    private final SearchService searchService;

    public SearchController(SearchService searchService) {
        this.searchService = searchService;
    }

    /**
     * @brief Handles GET /search requests with hyperparameter tuning.
     */
    @Override
    public CompletableFuture<ResponseEntity<SearchResponse>> search(
            String query, Integer page, Integer size, String fuzziness,
            Float phraseBoost, Float titleBoost, Integer slop,
            Boolean highlight, Boolean spellCheck) {

        int currentPage = (page != null) ? page : 1;
        int pageSize    = (size != null) ? size : 10;

        return CompletableFuture.supplyAsync(() -> {
            SearchResponse response = searchService.search(
                query, currentPage, pageSize, fuzziness, phraseBoost, titleBoost, slop, highlight
            );
            return ResponseEntity.ok(response);
        });
    }
}
